name: iOS Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Unzip project
      run: |
        unzip *.zip -d .
        find . -name "*.xcodeproj"

    - name: Detect Xcode project
      id: detect
      run: |
        FILE=$(find . -name "*.xcodeproj" | head -n 1)
        echo "project=$FILE" >> $GITHUB_OUTPUT

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "16.2"

    - name: Build iOS Simulator
      run: |
        xcodebuild \
          -project "${{ steps.detect.outputs.project }}" \
          -scheme JunwooBrowserTOTAL \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          build
