jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.1.1"

      - name: Build iOS App
        run: |
          xcodebuild \
            -project ./JunwooBrowserTOTAL/JunwooBrowserTOTAL.xcodeproj \
            -scheme JunwooBrowserTOTAL \
            -sdk iphonesimulator \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            build
