    - name: Unzip project
      run: |
        unzip *.zip -d .
        find . -name "*.xcodeproj" -maxdepth 3

    - name: Detect Xcode project
      id: detect
      run: |
        FILE=$(find . -name "*.xcodeproj" -maxdepth 3 | head -n 1)
        echo "project=$FILE" >> $GITHUB_OUTPUT
        echo "Detected project: $FILE"

    - name: Build iOS Simulator
      run: |
        xcodebuild \
          -project "${{ steps.detect.outputs.project }}" \
          -scheme JunwooBrowserTOTAL \
          -sdk iphonesimulator \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          build
